# Install pre-commit hooks via
# pre-commit install

exclude: (graphviz.py|graphviz_wrap.c)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: bc7af46104f0f5368b95878decf720f9f00c2559 # frozen: v3.4.2
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d7f0995508bdaeb0a1f4a838500d6a0a1fc6ec7b # frozen: v0.9.5
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 78a9dcbecf4f755f65d1f3dec556bc249d723600 # frozen: 1.19.1
    hooks:
      - id: blacken-docs
